analyzer:
  exclude:
    - lib/generated/*.dart
    - lib/generated/*/*.dart
    - lib/data/database/*.g.dart
    - lib/data/repository/*.g.dart
  enable-experiment:
    - extension-methods

include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
