name: Blackout
description: Keep track of your supplies

version: 1.0.0+1

environment:
  sdk: ">=2.8.0-dev.12.0.flutter-9983424a3c"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: 1.1.0
  flushbar: 1.9.1
  flutter_bloc: 3.2.0
  flutter_cupertino_localizations: 1.0.1
  flutter_launcher_icons: 0.7.4
  get_it: 3.1.0
  package_info: 0.4.0+13
  path_provider: 1.6.0
  pub_semver: 1.4.3
  shared_preferences: 0.5.6+1
  validators: 2.0.0+1
  path: 1.6.4
  moor: 2.4.2
  moor_ffi: 0.4.0
  uuid: 2.0.4
  time_machine: 0.9.12
  optional: 4.1.0
  flutter_swiper: 1.1.6
  qr_code_scanner: 0.0.12
  flutter_is_emulator: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: 2.4.0
  json_serializable: 3.2.5
  build_runner: 1.8.0

flutter:
  uses-material-design: true

  assets:
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

flutter_intl:
  enabled: true
