name: Blackout
description: Keep track of your supplies

version: 1.0.0+1

environment:
  sdk: ">=2.9.0-9.0.dev.flutter-2676764792"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 2.1.0
  barcode_scan: 3.0.1
  bloc_test: 5.1.0
  cupertino_icons: ^0.1.3
  equatable: 1.1.1
  flui: 0.9.2
  flushbar: 1.10.2
  flutter_bloc: 4.0.0
  flutter_cupertino_localizations: 1.0.1
  flutter_is_emulator: 1.0.0
  flutter_launcher_icons: 0.7.5
  flutter_swiper: 1.1.6
  get_it: 4.0.2
  intl: 0.16.1
  jiffy: 3.0.1
  mockito: 4.1.1
  moor: 3.0.2
  moor_ffi: 0.5.0
  optional: 4.1.0
  package_info: 0.4.0+18
  path: 1.7.0
  path_provider: 1.6.0
  pub_semver: 1.4.4
  qr_code_scanner: 0.0.13
  shared_preferences: 0.5.7+2
  super_enum: 0.4.2
  time_machine: 0.9.12
  uuid: 2.0.4
  validators: 2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.0
  json_serializable: 3.3.0
  moor_generator: 3.0.0
  super_enum_generator: 0.5.0

flutter:
  uses-material-design: true

  assets:
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

flutter_intl:
  enabled: true
