name: Blackout
description: Keep track of your supplies

version: 1.0.0+1

environment:
  sdk: ">=2.8.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 2.1.0
  barcode_scan: 3.0.1
  bloc_test: 5.1.0
  cupertino_icons: ^0.1.3
  device_info: 0.4.2+4
  equatable: 1.2.0
  flushbar: 1.10.4
  flutter_bloc: 4.0.1
  flutter_cupertino_localizations: 1.0.1
  flutter_launcher_icons: 0.7.5
  flutter_speed_dial: 1.2.5
  flutter_swiper: 1.1.6
  flutter_typeahead: 1.8.5
  flutter_whatsnew: 1.0.3
  get_it: 4.0.2
  intl: 0.16.1
  jiffy: 3.0.1
  mockito: 4.1.1
  moor: 3.2.0
  moor_ffi: 0.7.0
  package_info: 0.4.1
  path: 1.7.0
  path_provider: 1.6.11
  permission_handler: 5.0.1+1
  pub_semver: 1.4.4
  qr_code_scanner: 0.0.13
  shared_preferences: 0.5.7+3
  time_machine: 0.9.12
  uuid: 2.1.0
  validators: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.0
  json_serializable: 3.3.0
  moor_generator: 3.1.0
  super_enum_generator: 0.5.0
  effective_dart: 1.2.3

flutter_icons:
  android: true
  ios: true
  image_path: assets/launcher/blackout.png
  adaptive_icon_background: assets/launcher/blackout_background.png
  adaptive_icon_foreground: assets/launcher/blackout_foreground.png

flutter:
  uses-material-design: true

  assets:
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
#    - documentation/changelog_en.md
#    - documentation/changelog_de.md

flutter_intl:
  enabled: true
  localizely:
    project_id: 3340b9f1-e852-4ccc-9146-cd4c1a387739
