name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Update to latest flutter version
        run: flutter upgrade

      - name: Install missing sqlite dependency
        run: sudo apt-get install -y libsqlite3-dev

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Check formatting issues
        run: dart tools/format.dart --set-exit-if-changed

      - name: Analyze dart code
        run: flutter analyze .

      - name: Tests
        run: flutter test
