name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      # latest flutter dev version
      - run: flutter upgrade

      # Install missing sqlite dependency
      - run: sudo apt-get install -y libsqlite3-dev

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: dart tools/format.dart --set-exit-if-changed

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test
